# Generated by Django 4.1 on 2022-11-15 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
